version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=impure
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
volumes:
  db:
    driver: local