version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=impure
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes:
      - ./src/main/resources/db/migration/V1__create_tables.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local